<div align=center>

| Nama                    | NRP        |
|:-----------------------:|:----------:|
| Aryan Shafa Wardana     | 5025211031 |
| Muhammad Ersya Vinorian | 5025211045 |

</div>

## Training Data

In [178]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

In [179]:
PROCESSED_DATA = 'data/processed/bald_probability.csv'

In [180]:
df = pd.read_csv(PROCESSED_DATA)

df

,age,gender,job_role,province,salary,is_married,is_hereditary,weight,height,shampoo,is_smoker,education,stress,bald_prob
0,27,0,1,5,7.957453e+06,1,0,54.315053,170.428542,3,1,0,5,Likely
1,53,0,1,3,7.633003e+06,1,0,72.873404,165.530097,3,0,0,7,Likely
2,37,0,0,3,6.637625e+06,1,0,46.321533,154.599388,2,0,0,4,Likely
3,36,0,2,22,3.624871e+06,1,0,51.539781,167.340481,0,1,2,9,More Likely
4,55,0,1,20,9.213032e+06,1,1,54.287045,179.235145,3,0,0,1,More Likely
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5860,43,1,0,30,7.495176e+06,1,0,57.817115,186.801200,2,1,5,9,More Likely
5861,21,0,0,26,5.326614e+06,1,1,50.257686,189.341664,1,0,0,6,Likely
5862,32,1,0,33,6.024409e+06,1,0,44.432438,154.578859,0,0,5,9,Likely
5863,34,1,0,15,1.007043e+07,1,0,49.389914,158.782726,4,1,0,9,Likely
5864,58,1,1,4,1.769162e+07,1,0,81.036287,183.054150,4,1,0,10,More Likely

#### Split training and testing data

In [181]:
y = df.pop('bald_prob')
X = df
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=0)

#### Artificial Neural Network

In [182]:
ann_model = MLPClassifier(solver='sgd', hidden_layer_sizes=(4, 4), alpha=0.001)
ann_model.fit(X_train, y_train)
ann_model.score(X_train, y_train)

0.6250913520097442

#### Support Vector Machine